sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
env:
  - PHPUNIT_GROUP=default

matrix:
  fast_finish: true
  allow_failures:
    - nightly
    - env: PHPUNIT_GROUP=integration

stages:
  - analyze
  - test

jobs:
  include:
    - if: branch != master
      php: 7.0
      env: PHPUNIT_GROUP=integration
    - stage: analyze
      php: 7.2
      install:
        - pecl install ast
        - phpenv config-rm xdebug.ini
        - composer install --prefer-dist
      script:
        - make ci-analyze --keep-going
        - composer validate

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - phpenv config-rm xdebug.ini || true
  - composer remove --no-update --dev phan/phan phpstan/phpstan vimeo/psalm infection/infection friendsofphp/php-cs-fixer
  - composer install --prefer-dist

script:
  - make ci-test --keep-going PHPUNIT_GROUP=$PHPUNIT_GROUP

after_success:
  - travis_retry php vendor/bin/php-coveralls
