sudo: false

language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - nightly

cache:
  directories:
    - $HOME/.composer
    - build/cache

install:
  - pecl install ast
  - composer install --prefer-dist

script:
  - make ci --keep-going COMPOSER='/bin/sh -c composer'
  - composer validate

after_success:
  - travis_retry php vendor/bin/php-coveralls
